export const translations = {
    en: {
        reportTitle: "Environmental Data Report",
        hospitalName: "Hospital Environment Control",
        reportDate: "Report Date",
        reportPeriod: "Report Period",
        generatedBy: "Generated by Hospital Environment Control System",

        configuration: "Report Configuration",
        dataType: "Data Type",
        granularity: "Data Granularity",
        hospitalArea: "Hospital Area",
        language: "Language",
        duration: "Duration",

        allDataTypes: "All Data Types",
        temperature: "Temperature",
        humidity: "Humidity",
        pressure: "Pressure",
        eco2: "eCO₂",
        tvoc: "TVOC",
        noise: "Noise",

        perMinute: "Per Minute",
        perHour: "Per Hour",
        perDay: "Per Day",
        perWeek: "Per Week",
        perMonth: "Per Month",

        pharmacy: "Pharmacy",
        icu: "ICU",
        reception: "Reception",
        emergencyRoom: "Emergency Room",
        surgery: "Surgery",
        laboratory: "Laboratory",

        statistics: "Statistics",
        average: "Average",
        minimum: "Minimum",
        maximum: "Maximum",
        standardDeviation: "Standard Deviation",
        median: "Median",
        countValid: "Count (Valid)",
        totalDataPoints: "Total Data Points",
        dataCompleteness: "Data Completeness",
        q1: "Q1 (25%)",
        q3: "Q3 (75%)",
        coeffVariation: "Coeff. of Variation",
        range: "Range",
        value: "Value",
        notAvailable: "N/A",
        frontendAggregated: "(Frontend Aggregated)",

        frequency: "Frequency",
        noData: "No Data",
        distribution: "Distribution",
        noValidData: "No Valid Data",
        allValuesEqual: "All values equal",
        errorGeneratingCharts: "Error generating charts for this data type",

        celsius: "°C",
        fahrenheit: "°F",
        percent: "%",
        pascal: "Pa",
        ppm: "ppm",
        decibels: "dB",
        days: "days",

        chartTitle: "Environmental Data Over Time",
        timeAxis: "Time",
        valueAxis: "Value",

        footer: "This report was automatically generated by the Hospital Environment Control System.",
        pageOf: "Page {current} of {total}"
    },

    de: {
        reportTitle: "Umweltdatenbericht",
        hospitalName: "Krankenhaus-Umweltkontrolle",
        reportDate: "Berichtsdatum",
        reportPeriod: "Berichtszeitraum",
        generatedBy: "Generiert vom Krankenhaus-Umweltkontrollsystem",

        configuration: "Berichtskonfiguration",
        dataType: "Datentyp",
        granularity: "Datengranularität",
        hospitalArea: "Krankenhausbereich",
        language: "Sprache",
        duration: "Dauer",

        allDataTypes: "Alle Datentypen",
        temperature: "Temperatur",
        humidity: "Feuchtigkeit",
        pressure: "Druck",
        eco2: "eCO₂",
        tvoc: "TVOC",
        noise: "Lärm",

        perMinute: "Pro Minute",
        perHour: "Pro Stunde",
        perDay: "Pro Tag",
        perWeek: "Pro Woche",
        perMonth: "Pro Monat",

        pharmacy: "Apotheke",
        icu: "Intensivstation",
        reception: "Rezeption",
        emergencyRoom: "Notaufnahme",
        surgery: "Chirurgie",
        laboratory: "Labor",

        statistics: "Statistiken",
        average: "Durchschnitt",
        minimum: "Minimum",
        maximum: "Maximum",
        standardDeviation: "Standardabweichung",
        median: "Median",
        countValid: "Anzahl (Gültig)",
        totalDataPoints: "Gesamte Datenpunkte",
        dataCompleteness: "Datenvollständigkeit",
        q1: "Q1 (25%)",
        q3: "Q3 (75%)",
        coeffVariation: "Variationskoeffizient",
        range: "Spannweite",
        value: "Wert",
        notAvailable: "N/V",
        frontendAggregated: "(Frontend-Aggregiert)",

        frequency: "Häufigkeit",
        noData: "Keine Daten",
        distribution: "Verteilung",
        noValidData: "Keine gültigen Daten",
        allValuesEqual: "Alle Werte gleich",
        errorGeneratingCharts: "Fehler beim Erstellen der Diagramme für diesen Datentyp",

        celsius: "°C",
        fahrenheit: "°F",
        percent: "%",
        pascal: "Pa",
        ppm: "ppm",
        decibels: "dB",
        days: "Tage",

        chartTitle: "Umweltdaten im Zeitverlauf",
        timeAxis: "Zeit",
        valueAxis: "Wert",

        footer: "Dieser Bericht wurde automatisch vom Krankenhaus-Umweltkontrollsystem erstellt.",
        pageOf: "Seite {current} von {total}"
    },

    tr: {
        reportTitle: "Çevresel Veri Raporu",
        hospitalName: "Hastane Çevre Kontrol",
        reportDate: "Rapor Tarihi",
        reportPeriod: "Rapor Dönemi",
        generatedBy: "Hastane Çevre Kontrol Sistemi tarafından oluşturulmuştur",

        dataType: "Veri Türü",
        granularity: "Veri Ayrıntısı",
        hospitalArea: "Hastane Alanı",
        language: "Dil",
        duration: "Süre",

        allDataTypes: "Tüm Veri Türleri",
        temperature: "Sıcaklık",
        humidity: "Nem",
        pressure: "Basınç",
        eco2: "eCO₂",
        tvoc: "TVOC",
        noise: "Gürültü",

        perMinute: "Dakikada",
        perHour: "Saatte",
        perDay: "Günde",
        perWeek: "Haftada",
        perMonth: "Ayda",

        pharmacy: "Eczane",
        icu: "Yoğun Bakım",
        reception: "Resepsiyon",
        emergencyRoom: "Acil Servis",
        surgery: "Ameliyathane",
        laboratory: "Laboratuvar",

        statistics: "İstatistikler",
        average: "Ortalama",
        minimum: "Minimum",
        maximum: "Maksimum",
        standardDeviation: "Standart Sapma",
        median: "Medyan",
        countValid: "Sayı (Geçerli)",
        totalDataPoints: "Toplam Veri Noktası",
        dataCompleteness: "Veri Tamlığı",
        q1: "Q1 (%25)",
        q3: "Q3 (%75)",
        coeffVariation: "Değişim Katsayısı",
        range: "Aralık",
        value: "Değer",
        notAvailable: "Mevcut Değil",
        frontendAggregated: "(Frontend Toplanmış)",

        frequency: "Frekans",
        noData: "Veri Yok",
        distribution: "Dağılım",
        noValidData: "Geçerli Veri Yok",
        allValuesEqual: "Tüm değerler eşit",
        errorGeneratingCharts: "Bu veri türü için grafik oluşturulurken hata oluştu",

        celsius: "°C",
        fahrenheit: "°F",
        percent: "%",
        pascal: "Pa",
        ppm: "ppm",
        decibels: "dB",
        days: "gün",

        chartTitle: "Zamanla Çevresel Veriler",
        timeAxis: "Zaman",
        valueAxis: "Değer",

        footer: "Bu rapor Hastane Çevre Kontrol Sistemi tarafından otomatik olarak oluşturulmuştur.",
        pageOf: "Sayfa {current} / {total}"
    },

    "pt-br": {
        reportTitle: "Relatório de Dados Ambientais",
        hospitalName: "Controle Ambiental Hospitalar",
        reportDate: "Data do Relatório",
        reportPeriod: "Período do Relatório",
        generatedBy: "Gerado pelo Sistema de Controle Ambiental Hospitalar",

        configuration: "Configuração do Relatório",
        dataType: "Tipo de Dados",
        granularity: "Granularidade dos Dados",
        hospitalArea: "Área Hospitalar",
        language: "Idioma",
        duration: "Duração",

        allDataTypes: "Todos os Tipos de Dados",
        temperature: "Temperatura",
        humidity: "Umidade",
        pressure: "Pressão",
        eco2: "eCO₂",
        tvoc: "TVOC",
        noise: "Ruído",

        perMinute: "Por Minuto",
        perHour: "Por Hora",
        perDay: "Por Dia",
        perWeek: "Por Semana",
        perMonth: "Por Mês",

        pharmacy: "Farmácia",
        icu: "UTI",
        reception: "Recepção",
        emergencyRoom: "Pronto Socorro",
        surgery: "Cirurgia",
        laboratory: "Laboratório",

        statistics: "Estatísticas",
        average: "Média",
        minimum: "Mínimo",
        maximum: "Máximo",
        standardDeviation: "Desvio Padrão",
        median: "Mediana",
        countValid: "Contagem (Válidos)",
        totalDataPoints: "Total de Pontos de Dados",
        dataCompleteness: "Completude dos Dados",
        q1: "Q1 (25%)",
        q3: "Q3 (75%)",
        coeffVariation: "Coef. de Variação",
        range: "Amplitude",
        value: "Valor",
        notAvailable: "N/D",
        frontendAggregated: "(Agregado no Frontend)",

        frequency: "Frequência",
        noData: "Sem Dados",
        distribution: "Distribuição",
        noValidData: "Sem Dados Válidos",
        allValuesEqual: "Todos os valores iguais",
        errorGeneratingCharts: "Erro ao gerar gráficos para este tipo de dados",

        celsius: "°C",
        fahrenheit: "°F",
        percent: "%",
        pascal: "Pa",
        ppm: "ppm",
        decibels: "dB",
        days: "dias",

        chartTitle: "Dados Ambientais ao Longo do Tempo",
        timeAxis: "Tempo",
        valueAxis: "Valor",

        footer: "Este relatório foi gerado automaticamente pelo Sistema de Controle Ambiental Hospitalar.",
        pageOf: "Página {current} de {total}"
    },

    es: {
        reportTitle: "Informe de Datos Ambientales",
        hospitalName: "Control Ambiental Hospitalario",
        reportDate: "Fecha del Informe",
        reportPeriod: "Período del Informe",
        generatedBy: "Generado por el Sistema de Control Ambiental Hospitalario",

        configuration: "Configuración del Informe",
        dataType: "Tipo de Datos",
        granularity: "Granularidad de Datos",
        hospitalArea: "Área Hospitalaria",
        language: "Idioma",
        duration: "Duración",

        allDataTypes: "Todos los Tipos de Datos",
        temperature: "Temperatura",
        humidity: "Humedad",
        pressure: "Presión",
        eco2: "eCO₂",
        tvoc: "TVOC",
        noise: "Ruido",

        perMinute: "Por Minuto",
        perHour: "Por Hora",
        perDay: "Por Día",
        perWeek: "Por Semana",
        perMonth: "Por Mes",

        pharmacy: "Farmacia",
        icu: "UCI",
        reception: "Recepción",
        emergencyRoom: "Urgencias",
        surgery: "Cirugía",
        laboratory: "Laboratorio",

        statistics: "Estadísticas",
        average: "Promedio",
        minimum: "Mínimo",
        maximum: "Máximo",
        standardDeviation: "Desviación Estándar",
        median: "Mediana",
        countValid: "Conteo (Válidos)",
        totalDataPoints: "Total de Puntos de Datos",
        dataCompleteness: "Completitud de Datos",
        q1: "Q1 (25%)",
        q3: "Q3 (75%)",
        coeffVariation: "Coef. de Variación",
        range: "Rango",
        value: "Valor",
        notAvailable: "N/D",
        frontendAggregated: "(Agregado en Frontend)",

        frequency: "Frecuencia",
        noData: "Sin Datos",
        distribution: "Distribución",
        noValidData: "Sin Datos Válidos",
        allValuesEqual: "Todos los valores iguales",
        errorGeneratingCharts: "Error al generar gráficos para este tipo de datos",

        celsius: "°C",
        fahrenheit: "°F",
        percent: "%",
        pascal: "Pa",
        ppm: "ppm",
        decibels: "dB",
        days: "días",

        chartTitle: "Datos Ambientales en el Tiempo",
        timeAxis: "Tiempo",
        valueAxis: "Valor",

        footer: "Este informe fue generado automáticamente por el Sistema de Control Ambiental Hospitalario.",
        pageOf: "Página {current} de {total}"
    }
};

export const getTranslation = (language, key) => {
    return translations[language]?.[key] || translations.en[key] || key;
};

export const formatNumber = (number, language) => {
    const locales = {
        'en': 'en-US',
        'de': 'de-DE',
        'tr': 'tr-TR',
        'pt-br': 'pt-BR',
        'es': 'es-ES'
    };

    return new Intl.NumberFormat(locales[language] || 'en-US', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
    }).format(number);
};

export const formatDate = (date, language) => {
    const locales = {
        'en': 'en-US',
        'de': 'de-DE',
        'tr': 'tr-TR',
        'pt-br': 'pt-BR',
        'es': 'es-ES'
    };

    let dateObj;
    if (typeof date === 'string' && date.match(/^\d{4}-\d{2}-\d{2}$/)) {
        const [year, month, day] = date.split('-').map(Number);
        dateObj = new Date(year, month - 1, day);
    } else {
        dateObj = new Date(date);
    }

    return dateObj.toLocaleDateString(locales[language] || 'en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });
};

