// Translations for the PDF reports
export const translations = {
    en: {
        // Report Header
        reportTitle: "Environmental Data Report",
        hospitalName: "Hospital Environment Control",
        reportDate: "Report Date",
        reportPeriod: "Report Period",
        generatedBy: "Generated by Hospital Environment Control System",

        // Report Configuration
        configuration: "Report Configuration",
        dataType: "Data Type",
        granularity: "Data Granularity",
        hospitalArea: "Hospital Area",
        language: "Language",
        duration: "Duration",

        // Data Types
        allDataTypes: "All Data Types",
        temperature: "Temperature",
        humidity: "Humidity",
        pressure: "Pressure",
        eco2: "eCO₂",
        tvoc: "TVOC",
        noise: "Noise",

        // Granularity
        perMinute: "Per Minute",
        perHour: "Per Hour",
        perDay: "Per Day",
        perWeek: "Per Week",
        perMonth: "Per Month",

        // Hospital Areas
        pharmacy: "Pharmacy",
        icu: "ICU",
        reception: "Reception",
        emergencyRoom: "Emergency Room",
        surgery: "Surgery",
        laboratory: "Laboratory",

        // Statistics
        statistics: "Statistics",
        average: "Average",
        minimum: "Minimum",
        maximum: "Maximum",
        standardDeviation: "Standard Deviation",

        // Units
        celsius: "°C",
        fahrenheit: "°F",
        percent: "%",
        pascal: "Pa",
        ppm: "ppm",
        decibels: "dB",
        days: "days",

        // Chart Titles
        chartTitle: "Environmental Data Over Time",
        timeAxis: "Time",
        valueAxis: "Value",

        // Footer
        footer: "This report was automatically generated by the Hospital Environment Control System.",
        pageOf: "Page {current} of {total}"
    },

    de: {
        // Report Header
        reportTitle: "Umweltdatenbericht",
        hospitalName: "Krankenhaus-Umweltkontrolle",
        reportDate: "Berichtsdatum",
        reportPeriod: "Berichtszeitraum",
        generatedBy: "Generiert vom Krankenhaus-Umweltkontrollsystem",

        // Report Configuration
        configuration: "Berichtskonfiguration",
        dataType: "Datentyp",
        granularity: "Datengranularität",
        hospitalArea: "Krankenhausbereich",
        language: "Sprache",
        duration: "Dauer",

        // Data Types
        allDataTypes: "Alle Datentypen",
        temperature: "Temperatur",
        humidity: "Feuchtigkeit",
        pressure: "Druck",
        eco2: "eCO₂",
        tvoc: "TVOC",
        noise: "Lärm",

        // Granularity
        perMinute: "Pro Minute",
        perHour: "Pro Stunde",
        perDay: "Pro Tag",
        perWeek: "Pro Woche",
        perMonth: "Pro Monat",

        // Hospital Areas
        pharmacy: "Apotheke",
        icu: "Intensivstation",
        reception: "Rezeption",
        emergencyRoom: "Notaufnahme",
        surgery: "Chirurgie",
        laboratory: "Labor",

        // Statistics
        statistics: "Statistiken",
        average: "Durchschnitt",
        minimum: "Minimum",
        maximum: "Maximum",
        standardDeviation: "Standardabweichung",

        // Units
        celsius: "°C",
        fahrenheit: "°F",
        percent: "%",
        pascal: "Pa",
        ppm: "ppm",
        decibels: "dB",
        days: "Tage",

        // Chart Titles
        chartTitle: "Umweltdaten im Zeitverlauf",
        timeAxis: "Zeit",
        valueAxis: "Wert",

        // Footer
        footer: "Dieser Bericht wurde automatisch vom Krankenhaus-Umweltkontrollsystem erstellt.",
        pageOf: "Seite {current} von {total}"
    },

    tr: {
        // Report Header
        reportTitle: "Çevresel Veri Raporu",
        hospitalName: "Hastane Çevre Kontrol",
        reportDate: "Rapor Tarihi",
        reportPeriod: "Rapor Dönemi",
        generatedBy: "Hastane Çevre Kontrol Sistemi tarafından oluşturulmuştur",

        // Report Configuration
        configuration: "Rapor Yapılandırması",
        dataType: "Veri Türü",
        granularity: "Veri Ayrıntısı",
        hospitalArea: "Hastane Alanı",
        language: "Dil",
        duration: "Süre",

        // Data Types
        allDataTypes: "Tüm Veri Türleri",
        temperature: "Sıcaklık",
        humidity: "Nem",
        pressure: "Basınç",
        eco2: "eCO₂",
        tvoc: "TVOC",
        noise: "Gürültü",

        // Granularity
        perMinute: "Dakikada",
        perHour: "Saatte",
        perDay: "Günde",
        perWeek: "Haftada",
        perMonth: "Ayda",

        // Hospital Areas
        pharmacy: "Eczane",
        icu: "Yoğun Bakım",
        reception: "Resepsiyon",
        emergencyRoom: "Acil Servis",
        surgery: "Ameliyathane",
        laboratory: "Laboratuvar",

        // Statistics
        statistics: "İstatistikler",
        average: "Ortalama",
        minimum: "Minimum",
        maximum: "Maksimum",
        standardDeviation: "Standart Sapma",

        // Units
        celsius: "°C",
        fahrenheit: "°F",
        percent: "%",
        pascal: "Pa",
        ppm: "ppm",
        decibels: "dB",
        days: "gün",

        // Chart Titles
        chartTitle: "Zamanla Çevresel Veriler",
        timeAxis: "Zaman",
        valueAxis: "Değer",

        // Footer
        footer: "Bu rapor Hastane Çevre Kontrol Sistemi tarafından otomatik olarak oluşturulmuştur.",
        pageOf: "Sayfa {current} / {total}"
    },

    "pt-br": {
        // Report Header
        reportTitle: "Relatório de Dados Ambientais",
        hospitalName: "Controle Ambiental Hospitalar",
        reportDate: "Data do Relatório",
        reportPeriod: "Período do Relatório",
        generatedBy: "Gerado pelo Sistema de Controle Ambiental Hospitalar",

        // Report Configuration
        configuration: "Configuração do Relatório",
        dataType: "Tipo de Dados",
        granularity: "Granularidade dos Dados",
        hospitalArea: "Área Hospitalar",
        language: "Idioma",
        duration: "Duração",

        // Data Types
        allDataTypes: "Todos os Tipos de Dados",
        temperature: "Temperatura",
        humidity: "Umidade",
        pressure: "Pressão",
        eco2: "eCO₂",
        tvoc: "TVOC",
        noise: "Ruído",

        // Granularity
        perMinute: "Por Minuto",
        perHour: "Por Hora",
        perDay: "Por Dia",
        perWeek: "Por Semana",
        perMonth: "Por Mês",

        // Hospital Areas
        pharmacy: "Farmácia",
        icu: "UTI",
        reception: "Recepção",
        emergencyRoom: "Pronto Socorro",
        surgery: "Cirurgia",
        laboratory: "Laboratório",

        // Statistics
        statistics: "Estatísticas",
        average: "Média",
        minimum: "Mínimo",
        maximum: "Máximo",
        standardDeviation: "Desvio Padrão",

        // Units
        celsius: "°C",
        fahrenheit: "°F",
        percent: "%",
        pascal: "Pa",
        ppm: "ppm",
        decibels: "dB",
        days: "dias",

        // Chart Titles
        chartTitle: "Dados Ambientais ao Longo do Tempo",
        timeAxis: "Tempo",
        valueAxis: "Valor",

        // Footer
        footer: "Este relatório foi gerado automaticamente pelo Sistema de Controle Ambiental Hospitalar.",
        pageOf: "Página {current} de {total}"
    },

    es: {
        // Report Header
        reportTitle: "Informe de Datos Ambientales",
        hospitalName: "Control Ambiental Hospitalario",
        reportDate: "Fecha del Informe",
        reportPeriod: "Período del Informe",
        generatedBy: "Generado por el Sistema de Control Ambiental Hospitalario",

        // Report Configuration
        configuration: "Configuración del Informe",
        dataType: "Tipo de Datos",
        granularity: "Granularidad de Datos",
        hospitalArea: "Área Hospitalaria",
        language: "Idioma",
        duration: "Duración",

        // Data Types
        allDataTypes: "Todos los Tipos de Datos",
        temperature: "Temperatura",
        humidity: "Humedad",
        pressure: "Presión",
        eco2: "eCO₂",
        tvoc: "TVOC",
        noise: "Ruido",

        // Granularity
        perMinute: "Por Minuto",
        perHour: "Por Hora",
        perDay: "Por Día",
        perWeek: "Por Semana",
        perMonth: "Por Mes",

        // Hospital Areas
        pharmacy: "Farmacia",
        icu: "UCI",
        reception: "Recepción",
        emergencyRoom: "Urgencias",
        surgery: "Cirugía",
        laboratory: "Laboratorio",

        // Statistics
        statistics: "Estadísticas",
        average: "Promedio",
        minimum: "Mínimo",
        maximum: "Máximo",
        standardDeviation: "Desviación Estándar",

        // Units
        celsius: "°C",
        fahrenheit: "°F",
        percent: "%",
        pascal: "Pa",
        ppm: "ppm",
        decibels: "dB",
        days: "días",

        // Chart Titles
        chartTitle: "Datos Ambientales en el Tiempo",
        timeAxis: "Tiempo",
        valueAxis: "Valor",

        // Footer
        footer: "Este informe fue generado automáticamente por el Sistema de Control Ambiental Hospitalario.",
        pageOf: "Página {current} de {total}"
    }
};

// Helper function to get translation
export const getTranslation = (language, key) => {
    return translations[language]?.[key] || translations.en[key] || key;
};

// Helper function to format numbers based on language
export const formatNumber = (number, language) => {
    const locales = {
        'en': 'en-US',
        'de': 'de-DE',
        'tr': 'tr-TR',
        'pt-br': 'pt-BR',
        'es': 'es-ES'
    };

    return new Intl.NumberFormat(locales[language] || 'en-US', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
    }).format(number);
};

// Helper function to format dates based on language
export const formatDate = (date, language) => {
    const locales = {
        'en': 'en-US',
        'de': 'de-DE',
        'tr': 'tr-TR',
        'pt-br': 'pt-BR',
        'es': 'es-ES'
    };

    // Se a data for uma string no formato "YYYY-MM-DD", criar a data de forma que seja interpretada no fuso horário local
    let dateObj;
    if (typeof date === 'string' && date.match(/^\d{4}-\d{2}-\d{2}$/)) {
        // Para strings no formato "YYYY-MM-DD", dividir e criar a data manualmente para evitar problemas de fuso horário
        const [year, month, day] = date.split('-').map(Number);
        dateObj = new Date(year, month - 1, day); // month - 1 porque Date usa meses baseados em zero
    } else {
        dateObj = new Date(date);
    }

    return dateObj.toLocaleDateString(locales[language] || 'en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });
};

